name: skiff
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: ericwindmill <ewindmill@greenbits.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  tavern: ^3.0.0
  build: any
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  build_test: any
